// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SignUpSuperGenius.Models;

namespace SignUpSuperGenius.Migrations
{
    [DbContext(typeof(AppointmentContext))]
    [Migration("20220323212509_combined")]
    partial class combined
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("SignUpSuperGenius.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Filled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AppointmentId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            Day = "Monday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "8:00am"
                        },
                        new
                        {
                            AppointmentId = 2,
                            Day = "Monday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "9:00am"
                        },
                        new
                        {
                            AppointmentId = 3,
                            Day = "Monday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "10:00am"
                        },
                        new
                        {
                            AppointmentId = 4,
                            Day = "Monday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "11:00am"
                        },
                        new
                        {
                            AppointmentId = 5,
                            Day = "Monday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "12:00pm"
                        },
                        new
                        {
                            AppointmentId = 6,
                            Day = "Monday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "1:00pm"
                        },
                        new
                        {
                            AppointmentId = 7,
                            Day = "Monday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "2:00pm"
                        },
                        new
                        {
                            AppointmentId = 8,
                            Day = "Monday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "3:00pm"
                        },
                        new
                        {
                            AppointmentId = 9,
                            Day = "Monday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "4:00pm"
                        },
                        new
                        {
                            AppointmentId = 10,
                            Day = "Monday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "5:00pm"
                        },
                        new
                        {
                            AppointmentId = 11,
                            Day = "Monday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "6:00pm"
                        },
                        new
                        {
                            AppointmentId = 12,
                            Day = "Monday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "7:00pm"
                        },
                        new
                        {
                            AppointmentId = 13,
                            Day = "Monday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "8:00pm"
                        },
                        new
                        {
                            AppointmentId = 14,
                            Day = "Tuesday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "8:00am"
                        },
                        new
                        {
                            AppointmentId = 15,
                            Day = "Tuesday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "9:00am"
                        },
                        new
                        {
                            AppointmentId = 16,
                            Day = "Tuesday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "10:00am"
                        },
                        new
                        {
                            AppointmentId = 17,
                            Day = "Tuesday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "11:00am"
                        },
                        new
                        {
                            AppointmentId = 18,
                            Day = "Tuesday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "12:00pm"
                        },
                        new
                        {
                            AppointmentId = 19,
                            Day = "Tuesday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "1:00pm"
                        },
                        new
                        {
                            AppointmentId = 20,
                            Day = "Tuesday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "2:00pm"
                        },
                        new
                        {
                            AppointmentId = 21,
                            Day = "Tuesday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "3:00pm"
                        },
                        new
                        {
                            AppointmentId = 22,
                            Day = "Tuesday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "4:00pm"
                        },
                        new
                        {
                            AppointmentId = 23,
                            Day = "Tuesday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "5:00pm"
                        },
                        new
                        {
                            AppointmentId = 24,
                            Day = "Tuesday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "6:00pm"
                        },
                        new
                        {
                            AppointmentId = 25,
                            Day = "Tuesday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "7:00pm"
                        },
                        new
                        {
                            AppointmentId = 26,
                            Day = "Tuesday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "8:00pm"
                        },
                        new
                        {
                            AppointmentId = 27,
                            Day = "Wednesday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "8:00am"
                        },
                        new
                        {
                            AppointmentId = 28,
                            Day = "Wednesday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "9:00am"
                        },
                        new
                        {
                            AppointmentId = 29,
                            Day = "Wednesday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "10:00am"
                        },
                        new
                        {
                            AppointmentId = 30,
                            Day = "Wednesday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "11:00am"
                        },
                        new
                        {
                            AppointmentId = 31,
                            Day = "Wednesday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "12:00pm"
                        },
                        new
                        {
                            AppointmentId = 32,
                            Day = "Wednesday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "1:00pm"
                        },
                        new
                        {
                            AppointmentId = 33,
                            Day = "Wednesday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "2:00pm"
                        },
                        new
                        {
                            AppointmentId = 34,
                            Day = "Wednesday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "3:00pm"
                        },
                        new
                        {
                            AppointmentId = 35,
                            Day = "Wednesday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "4:00pm"
                        },
                        new
                        {
                            AppointmentId = 36,
                            Day = "Wednesday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "5:00pm"
                        },
                        new
                        {
                            AppointmentId = 37,
                            Day = "Wednesday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "6:00pm"
                        },
                        new
                        {
                            AppointmentId = 38,
                            Day = "Wednesday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "7:00pm"
                        },
                        new
                        {
                            AppointmentId = 39,
                            Day = "Wednesday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "8:00pm"
                        },
                        new
                        {
                            AppointmentId = 40,
                            Day = "Thursday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "8:00am"
                        },
                        new
                        {
                            AppointmentId = 41,
                            Day = "Thursday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "9:00am"
                        },
                        new
                        {
                            AppointmentId = 42,
                            Day = "Thursday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "10:00am"
                        },
                        new
                        {
                            AppointmentId = 43,
                            Day = "Thursday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "11:00am"
                        },
                        new
                        {
                            AppointmentId = 44,
                            Day = "Thursday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "12:00pm"
                        },
                        new
                        {
                            AppointmentId = 45,
                            Day = "Thursday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "1:00pm"
                        },
                        new
                        {
                            AppointmentId = 46,
                            Day = "Thursday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "2:00pm"
                        },
                        new
                        {
                            AppointmentId = 47,
                            Day = "Thursday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "3:00pm"
                        },
                        new
                        {
                            AppointmentId = 48,
                            Day = "Thursday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "4:00pm"
                        },
                        new
                        {
                            AppointmentId = 49,
                            Day = "Thursday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "5:00pm"
                        },
                        new
                        {
                            AppointmentId = 50,
                            Day = "Thursday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "6:00pm"
                        },
                        new
                        {
                            AppointmentId = 51,
                            Day = "Thursday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "7:00pm"
                        },
                        new
                        {
                            AppointmentId = 52,
                            Day = "Thursday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "8:00pm"
                        },
                        new
                        {
                            AppointmentId = 53,
                            Day = "Friday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "8:00am"
                        },
                        new
                        {
                            AppointmentId = 54,
                            Day = "Friday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "9:00am"
                        },
                        new
                        {
                            AppointmentId = 55,
                            Day = "Friday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "10:00am"
                        },
                        new
                        {
                            AppointmentId = 56,
                            Day = "Friday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "11:00am"
                        },
                        new
                        {
                            AppointmentId = 57,
                            Day = "Friday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "12:00pm"
                        },
                        new
                        {
                            AppointmentId = 58,
                            Day = "Friday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "1:00pm"
                        },
                        new
                        {
                            AppointmentId = 59,
                            Day = "Friday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "2:00pm"
                        },
                        new
                        {
                            AppointmentId = 60,
                            Day = "Friday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "3:00pm"
                        },
                        new
                        {
                            AppointmentId = 61,
                            Day = "Friday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "4:00pm"
                        },
                        new
                        {
                            AppointmentId = 62,
                            Day = "Friday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "5:00pm"
                        },
                        new
                        {
                            AppointmentId = 63,
                            Day = "Friday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "6:00pm"
                        },
                        new
                        {
                            AppointmentId = 64,
                            Day = "Friday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "7:00pm"
                        },
                        new
                        {
                            AppointmentId = 65,
                            Day = "Friday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "8:00pm"
                        },
                        new
                        {
                            AppointmentId = 66,
                            Day = "Saturday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "8:00am"
                        },
                        new
                        {
                            AppointmentId = 67,
                            Day = "Saturday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "9:00am"
                        },
                        new
                        {
                            AppointmentId = 68,
                            Day = "Saturday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "10:00am"
                        },
                        new
                        {
                            AppointmentId = 69,
                            Day = "Saturday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "11:00am"
                        },
                        new
                        {
                            AppointmentId = 70,
                            Day = "Saturday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "12:00pm"
                        },
                        new
                        {
                            AppointmentId = 71,
                            Day = "Saturday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "1:00pm"
                        },
                        new
                        {
                            AppointmentId = 72,
                            Day = "Saturday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "2:00pm"
                        },
                        new
                        {
                            AppointmentId = 73,
                            Day = "Saturday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "3:00pm"
                        },
                        new
                        {
                            AppointmentId = 74,
                            Day = "Saturday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "4:00pm"
                        },
                        new
                        {
                            AppointmentId = 75,
                            Day = "Saturday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "5:00pm"
                        },
                        new
                        {
                            AppointmentId = 76,
                            Day = "Saturday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "6:00pm"
                        },
                        new
                        {
                            AppointmentId = 77,
                            Day = "Saturday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "7:00pm"
                        },
                        new
                        {
                            AppointmentId = 78,
                            Day = "Saturday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "8:00pm"
                        },
                        new
                        {
                            AppointmentId = 79,
                            Day = "Sunday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "8:00am"
                        },
                        new
                        {
                            AppointmentId = 80,
                            Day = "Sunday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "9:00am"
                        },
                        new
                        {
                            AppointmentId = 81,
                            Day = "Sunday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "10:00am"
                        },
                        new
                        {
                            AppointmentId = 82,
                            Day = "Sunday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "11:00am"
                        },
                        new
                        {
                            AppointmentId = 83,
                            Day = "Sunday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "12:00pm"
                        },
                        new
                        {
                            AppointmentId = 84,
                            Day = "Sunday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "1:00pm"
                        },
                        new
                        {
                            AppointmentId = 85,
                            Day = "Sunday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "2:00pm"
                        },
                        new
                        {
                            AppointmentId = 86,
                            Day = "Sunday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "3:00pm"
                        },
                        new
                        {
                            AppointmentId = 87,
                            Day = "Sunday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "4:00pm"
                        },
                        new
                        {
                            AppointmentId = 88,
                            Day = "Sunday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "5:00pm"
                        },
                        new
                        {
                            AppointmentId = 89,
                            Day = "Sunday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "6:00pm"
                        },
                        new
                        {
                            AppointmentId = 90,
                            Day = "Sunday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "7:00pm"
                        },
                        new
                        {
                            AppointmentId = 91,
                            Day = "Sunday",
                            Filled = false,
                            Size = (ushort)0,
                            Time = "8:00pm"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
